name: Build & Deploy
on:
  push: 
   branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React and Express App
        uses: appleboy/ssh-action@0.1.2
        with: 
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: ï½œ
            mkdir test
            cd test
            git clone git@https://github.com/agiledev-students-fall2022/final-project-team-decider
            echo 'Success'
      
